Catkin-ProjectName: ros_comm
Version: 1.8.9  # also update version in clients/cpp/roscpp/include/ros/common.h
Depends: catkin, genmsg, std_msgs, roscpp_core, ros,
         apr, boost, log4cxx, python-paramiko, python-yaml
Description: ROS communications-related libraries and tools
Author: Morgan Quigley <mquigley@cs.stanford.edu>, Troy Straszheim <straszheim@willowgarage.com>, Josh Faust, Brian Gerkey, Tim Field, Jeremy Leibs, Ken Conley et al
Maintainer: Ken Conley <kwc@willowgarage.com>
Homepage: http://www.ros.org


Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
